name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # update 2x sehari
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: gstngurah
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
